# Model Configuration
model:
  architecture: "sequential"
  input_shape: [FEATURES_COUNT]  # Replace FEATURES_COUNT with the actual number of features
  layers:
    - units: 128
      activation: "relu"
      kernel_regularizer:
        type: "L2"
        value: 0.105
    - units: 64
      activation: "relu"
      kernel_regularizer:
        type: "L2"
        value: 0.105
    - units: 32
      activation: "relu"
      kernel_regularizer:
        type: "L2"
        value: 0.105
    - units: 1
      activation: "sigmoid"
      kernel_regularizer:
        type: "L2"
        value: 0.105
  loss: "binary_crossentropy"
  optimizer:
    type: "adam"
    learning_rate: 0.0001
  metrics:
    - "accuracy"

# Training Configuration
training:
  epochs: 200
  verbose: 2
  validation_split: 0.2
